---
/Users/Connor/repos/personal:
  name: Connor Atherton
  email: c.liam.atherton@gmail.com
/Users/Connor/repos/bitnami:
  name: Connor Atherton
  email: connor@bitnami.com
/Users/Connor/.dotfiles:
  name: Connor Atherton
  email: c.liam.atherton@gmail.com
